Hw1
alex-pletnev/tinkoff pull request #1
Opened 2023-10-15 10:06 UTC by alex-pletnev

2023-10-16 06:00 UTC, nexen505 requested changes

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task0.java
> +    public void run() {
Предложение: в учебных целях можно написать тест на проверку вывода логирования с использованием, например, https://github.com/stefanbirkner/system-lambda#systemout-and-systemerr

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task1.java
> +        int min = Integer.parseInt(input.split(":")[0]);
Предложение: вынести результат `input.split(":")` в переменную, чтобы не считать его дважды.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task1.java
> +        final int SECOND_LIMIT = 60;
Косметика: обычно подобные константы выносят в приватные статические поля - стоит так сделать.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task1.java
> +        if (sek >= SECOND_LIMIT) {
Проблема: думаю, что отрицательное число секунд тоже надо считать некорректным, что здесь не учтено.

Предложение: добавить соответствующую логическую проверку и соответствующий тест.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task2.java
> +            divisor *= NEXT_NUMBER_ORDER;
Предложение: для упрощения стоит развернуть решение так, чтобы уменьшалось рассматриваемое число, а не рос делитель.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task3.java
> +        return a1min > a2min && a1max < a2max;
Проблема: в такой реализации максимумы будут считаться даже, если массивы не вложены, исходя из минимумов.

Предложение: изменить логику, чтобы функции выходила сразу, если минимумы показали невложенность, и максимумы не считались.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task4.java
> +            if (charArray.length % 2 == 1 && i + 1 == charArray.length) {
Предложение: учесть это в граничных условиях цикла для упрощения логики.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task4.java
> +        char tmp;
Косметика: эта переменная вне цикла не используется - не имеет смысла объявлять ее здесь, когда можно ее объявить внутри цикла.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task6.java
> +        reverseArray(chars);
Мысль: можно уйти от переворачивания массива, использовав предыдущую сортировку с указанием порядка по убыванию.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task6.java
> +    private int getAscending(int number) {
Проблема: здесь и в соседнем методе логика сильно усложняется из-за того, что оперирует символами, а не цифрами, и опирается на неявное знание, что число четырехзначное. 

Предложение: перейти к манипуляции цифрами и уйти от учета четырехзначности на уровне логики.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task6.java
> +    public int countK(int number) {
Проблема: по заданию функция должна быть рекурсивной, что не так.

Предложение: изменить реализацию в соответствии с требованиями.

2023-10-16 06:00 UTC, nexen505 commented on src/main/java/edu/hw1/Task7.java
> +public class Task7 {
Предложение: учесть в тестах и логике отрицательные значения сдвига.

2023-10-16 12:35 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task0.java
> +    public void run() {
добавил тест (с использованием Mockito)

2023-10-16 12:35 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task1.java
> +        int min = Integer.parseInt(input.split(":")[0]);
добавил переменную split

2023-10-16 12:36 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task1.java
> +        final int SECOND_LIMIT = 60;
вынес в приватное статическое поле

2023-10-16 12:36 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task1.java
> +        if (sek >= SECOND_LIMIT) {
исправил недоработку и добавил тест

2023-10-16 12:38 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task2.java
> +            divisor *= NEXT_NUMBER_ORDER;
решение развернул. Мне не совсем понятно, почему проще уменьшать рассматриваемое, а не увеличивать делитель?

2023-10-16 12:39 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task4.java
> +        char tmp;
переместил ее объявление в цикл

2023-10-16 12:41 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task6.java
> +        reverseArray(chars);
убрал метод reverseArray, использовал вместо него Arrays.sort(nums, Comparator.reverseOrder());

2023-10-16 12:42 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task6.java
> +    private int getAscending(int number) {
перешел к манипуляции цифрами и ушел от учета четырехзначности на уровне логики

2023-10-16 12:43 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task6.java
> +    public int countK(int number) {
Да, прошу прощения, невнимательно прочитал задание, теперь там рекурсия

2023-10-16 12:44 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task7.java
> +public class Task7 {
добавил корректную работу с отрицательными значениями сдвига и соотвествующие тесты

2023-10-17 05:52 UTC, nexen505 requested changes
Осталось прям немного по правкам)

Напомню еще раз проверить, есть ли у меня тут доступ на запись: не могу закрывать прежние мысли по ревью.

2023-10-17 05:52 UTC, nexen505 commented on src/main/java/edu/hw1/Task2.java
> +            div = num / PREVIOUS_NUMBER_ORDER;
Мысль: обращу внимание, что после выполнения тела цикла `div` и `num` приобретут одно и то же значение.

Предложение: использовать только `num`.

2023-10-17 05:52 UTC, nexen505 commented on src/main/java/edu/hw1/Task4.java
> +        for (int i = 0; i < charArray.length
Мысль: граничное условие можно упростить. Подскажу подумать, важен ли нам с точки зрения `i` последний символ строки любой длины.

2023-10-17 14:24 UTC, alex-pletnev commented
Пригласил вас во вкладке collaborators

2023-10-17 14:33 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task2.java
> +            div = num / PREVIOUS_NUMBER_ORDER;
удалил ненужную строку, немного изменил код

2023-10-17 14:34 UTC, alex-pletnev commented on src/main/java/edu/hw1/Task4.java
> +        for (int i = 0; i < charArray.length
И в правду, удалил излишнее условие, терерь for идет только до i < charArray.length - 1, код стал проще, спасибо за замечание!

2023-10-19 12:42 UTC, alex-pletnev commented
@nexen505 можно мерджить?

2023-10-22 09:17 UTC, merged